[package]
name = "mun_compiler"
version = "0.2.0"
authors = ["The Mun Team <team@mun-lang.org>"]
edition = "2018"
description = "Binary compilation functionality for Mun"
documentation = "https://docs.mun-lang.org/v0.2"
readme = "README.md"
homepage = "https://mun-lang.org"
repository = "https://github.com/mun-lang/mun"
license = "MIT OR Apache-2.0"
keywords = ["game", "hot-reloading", "language", "mun", "scripting"]
categories = ["game-development", "mun"]

[dependencies]
anyhow = "1.0.31"
mun_codegen = { version = "=0.2.0", path="../mun_codegen" }
mun_syntax = { version = "=0.2.0", path="../mun_syntax" }
mun_hir = { version = "=0.2.0", path="../mun_hir" }
mun_target = { version = "=0.2.0", path="../mun_target" }
annotate-snippets = { version = "0.6.1", features = ["color"] }
unicode-segmentation = "1.6.0"
ansi_term = "0.12.1"

[dev-dependencies]
insta = "0.16"
