language = "C"
cpp_compat = true

include_guard = "MUN_RUNTIME_BINDINGS_H_"
include_version = false
sys_includes = ["stdbool.h", "stdint.h"]
no_includes = true

line_length = 100
tab_width = 4

[export]
prefix = "Mun"

[enum]
rename_variants = "QualifiedScreamingSnakeCase"

[parse]
parse_deps = true
include = ["mun_abi", "mun_memory", "mun_runtime", "mun_capi_utils"]
extra_bindings = ["mun_memory", "mun_capi_utils"]
