[package]
name = "tools"
version = "0.3.0"
authors = ["The Mun Team <team@mun-lang.org>"]
edition = "2021"

[dependencies]
tera = { version = "1.15.0", default-features = false }
clap = { version="4.0.15", features=["derive"] }
anyhow = "1.0.31"
ron = "0.8.0"
cbindgen = { version = "0.24.3", default-features = false }
difference = "2.0"
heck = "0.4.0"
