[package]
name = "tools"
version = "0.3.0"
authors = ["The Mun Team <team@mun-lang.org>"]
edition = "2021"

[dependencies]
anyhow = "1.0.31"
cbindgen = { version = "0.24.3", default-features = false }
clap = { version="3.1.18", features = ["derive"] }
difference = "2.0"
heck = "0.4.0"
ron = "0.8.0"
tera = { version = "1.15.0", default-features = false }
