[package]
name = "tools"
version = "0.2.0"
authors = ["The Mun Team <team@mun-lang.org>"]
edition = "2018"

[dependencies]
teraron = "0.1.0"
clap = "2.32.0"
anyhow = "1.0.31"
ron = "0.4.2"
cbindgen = "= 0.14.2"
bindgen = "0.54"
difference = "2.0"
