[package]
name = "tools"
version = "0.3.0"
authors = ["The Mun Team <team@mun-lang.org>"]
edition = "2021"

[dependencies]
tera = "1.15.0"
clap = "2.32.0"
anyhow = "1.0.31"
ron = "0.7.0"
cbindgen = "= 0.16.0"
difference = "2.0"
heck = "0.4.0"
