[package]
name = "tools"
version = "0.3.0"
authors.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
cbindgen = { workspace = true }
clap = { workspace = true, features = ["derive", "std"] }
difference = { workspace = true }
heck = { workspace = true }
ron = { workspace = true }
tera = { workspace = true }

[lints]
workspace = true
