[package]
name = "mun_symbols"
version = "0.1.0"
authors = ["Wodann <remco.kuijper@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.3"
libloading = "0.5"
uuid = "0.7.4"
