[book]
authors = ["The Mun Team <team@mun-lang.org>"]
language = "en"
multilingual = false
src = "src"
title = "The Mun Programming Language"

[output.html]
additional-css = ["theme/mun.css"]
additional-js = ["theme/trailing_slash_hack.js"]
git-repository-url = "https://github.com/mun-lang/mun/tree/master/book"
